// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: msgdata.proto

package pbf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MSGID int32

const (
	MSGID_SIGNUP         MSGID = 0
	MSGID_SIGNIN         MSGID = 1
	MSGID_ROOMINFO       MSGID = 2
	MSGID_CREATEROOM     MSGID = 3
	MSGID_ENTERROOM      MSGID = 4
	MSGID_LEAVEROOM      MSGID = 5
	MSGID_ISREADY        MSGID = 6
	MSGID_HEART          MSGID = 7
	MSGID_STARTGAME      MSGID = 20
	MSGID_SETPID         MSGID = 21
	MSGID_LOADMAP        MSGID = 22
	MSGID_GAMEFIN        MSGID = 23
	MSGID_SYNCPHV        MSGID = 24
	MSGID_HWAVEWEAPON    MSGID = 25
	MSGID_PLACECUBE      MSGID = 26
	MSGID_ATK            MSGID = 27
	MSGID_COLLISION      MSGID = 28
	MSGID_ADDSCORE       MSGID = 29
	MSGID_VOICE          MSGID = 30
	MSGID_BROROOMCHANGE  MSGID = 104
	MSGID_BROISREADY     MSGID = 106
	MSGID_BROENTERGAME   MSGID = 122
	MSGID_BROGAMETIME    MSGID = 123
	MSGID_BROSYNCPHV     MSGID = 124
	MSGID_BROHWAVEWEAPON MSGID = 125
	MSGID_BROPLACEWEAPON MSGID = 126
	MSGID_BROATK         MSGID = 127
	MSGID_BROCOLLISION   MSGID = 128
	MSGID_BROADDSCORE    MSGID = 129
	MSGID_BROVOICE       MSGID = 130
)

// Enum value maps for MSGID.
var (
	MSGID_name = map[int32]string{
		0:   "SIGNUP",
		1:   "SIGNIN",
		2:   "ROOMINFO",
		3:   "CREATEROOM",
		4:   "ENTERROOM",
		5:   "LEAVEROOM",
		6:   "ISREADY",
		7:   "HEART",
		20:  "STARTGAME",
		21:  "SETPID",
		22:  "LOADMAP",
		23:  "GAMEFIN",
		24:  "SYNCPHV",
		25:  "HWAVEWEAPON",
		26:  "PLACECUBE",
		27:  "ATK",
		28:  "COLLISION",
		29:  "ADDSCORE",
		30:  "VOICE",
		104: "BROROOMCHANGE",
		106: "BROISREADY",
		122: "BROENTERGAME",
		123: "BROGAMETIME",
		124: "BROSYNCPHV",
		125: "BROHWAVEWEAPON",
		126: "BROPLACEWEAPON",
		127: "BROATK",
		128: "BROCOLLISION",
		129: "BROADDSCORE",
		130: "BROVOICE",
	}
	MSGID_value = map[string]int32{
		"SIGNUP":         0,
		"SIGNIN":         1,
		"ROOMINFO":       2,
		"CREATEROOM":     3,
		"ENTERROOM":      4,
		"LEAVEROOM":      5,
		"ISREADY":        6,
		"HEART":          7,
		"STARTGAME":      20,
		"SETPID":         21,
		"LOADMAP":        22,
		"GAMEFIN":        23,
		"SYNCPHV":        24,
		"HWAVEWEAPON":    25,
		"PLACECUBE":      26,
		"ATK":            27,
		"COLLISION":      28,
		"ADDSCORE":       29,
		"VOICE":          30,
		"BROROOMCHANGE":  104,
		"BROISREADY":     106,
		"BROENTERGAME":   122,
		"BROGAMETIME":    123,
		"BROSYNCPHV":     124,
		"BROHWAVEWEAPON": 125,
		"BROPLACEWEAPON": 126,
		"BROATK":         127,
		"BROCOLLISION":   128,
		"BROADDSCORE":    129,
		"BROVOICE":       130,
	}
)

func (x MSGID) Enum() *MSGID {
	p := new(MSGID)
	*p = x
	return p
}

func (x MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msgdata_proto_enumTypes[0].Descriptor()
}

func (MSGID) Type() protoreflect.EnumType {
	return &file_msgdata_proto_enumTypes[0]
}

func (x MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSGID.Descriptor instead.
func (MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{0}
}

//注册账户
type SignUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID      string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *SignUp) Reset() {
	*x = SignUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUp) ProtoMessage() {}

func (x *SignUp) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUp.ProtoReflect.Descriptor instead.
func (*SignUp) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{0}
}

func (x *SignUp) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *SignUp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//登录账户
type SignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID      string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *SignIn) Reset() {
	*x = SignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn) ProtoMessage() {}

func (x *SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn.ProtoReflect.Descriptor instead.
func (*SignIn) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{1}
}

func (x *SignIn) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *SignIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

//用户信息
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID      string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Rank     int32  `protobuf:"varint,4,opt,name=Rank,proto3" json:"Rank,omitempty"`
	EXP      int32  `protobuf:"varint,5,opt,name=EXP,proto3" json:"EXP,omitempty"`
	HeadIcon int32  `protobuf:"varint,6,opt,name=HeadIcon,proto3" json:"HeadIcon,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *User) GetEXP() int32 {
	if x != nil {
		return x.EXP
	}
	return 0
}

func (x *User) GetHeadIcon() int32 {
	if x != nil {
		return x.HeadIcon
	}
	return 0
}

//登录/注册是否成功
type SignSucc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag     bool  `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	UserInfo *User `protobuf:"bytes,2,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *SignSucc) Reset() {
	*x = SignSucc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignSucc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignSucc) ProtoMessage() {}

func (x *SignSucc) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignSucc.ProtoReflect.Descriptor instead.
func (*SignSucc) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{3}
}

func (x *SignSucc) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *SignSucc) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

//玩家位置和移动速度
type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos   *Vector `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rot   *Vector `protobuf:"bytes,2,opt,name=Rot,proto3" json:"Rot,omitempty"`
	Speed float32 `protobuf:"fixed32,3,opt,name=Speed,proto3" json:"Speed,omitempty"`
	Pid   int32   `protobuf:"varint,4,opt,name=Pid,proto3" json:"Pid,omitempty"`
	HP    float32 `protobuf:"fixed32,5,opt,name=HP,proto3" json:"HP,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetPos() *Vector {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Player) GetRot() *Vector {
	if x != nil {
		return x.Rot
	}
	return nil
}

func (x *Player) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Player) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Player) GetHP() float32 {
	if x != nil {
		return x.HP
	}
	return 0
}

//向量
type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{5}
}

func (x *Vector) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

//玩家举起方块
type HaveWeapon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID int32 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	CID int32 `protobuf:"varint,2,opt,name=CID,proto3" json:"CID,omitempty"`
}

func (x *HaveWeapon) Reset() {
	*x = HaveWeapon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HaveWeapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaveWeapon) ProtoMessage() {}

func (x *HaveWeapon) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaveWeapon.ProtoReflect.Descriptor instead.
func (*HaveWeapon) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{6}
}

func (x *HaveWeapon) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *HaveWeapon) GetCID() int32 {
	if x != nil {
		return x.CID
	}
	return 0
}

//玩家广播的数据
type PlayerAtk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid       int32   `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	AttackDir *Vector `protobuf:"bytes,2,opt,name=AttackDir,proto3" json:"AttackDir,omitempty"`
}

func (x *PlayerAtk) Reset() {
	*x = PlayerAtk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAtk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAtk) ProtoMessage() {}

func (x *PlayerAtk) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAtk.ProtoReflect.Descriptor instead.
func (*PlayerAtk) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerAtk) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PlayerAtk) GetAttackDir() *Vector {
	if x != nil {
		return x.AttackDir
	}
	return nil
}

//创建/进入/离开房间
type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid int32 `protobuf:"varint,1,opt,name=Rid,proto3" json:"Rid,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{8}
}

func (x *Room) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

//房间信息
type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`              //房间id
	Nums      int32  `protobuf:"varint,2,opt,name=Nums,proto3" json:"Nums,omitempty"`          //房间人数
	OwnerName string `protobuf:"bytes,3,opt,name=OwnerName,proto3" json:"OwnerName,omitempty"` //房主Name
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{9}
}

func (x *RoomInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomInfo) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *RoomInfo) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

//房间列表信息
type RoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomlist []*RoomInfo `protobuf:"bytes,1,rep,name=roomlist,proto3" json:"roomlist,omitempty"`
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{10}
}

func (x *RoomList) GetRoomlist() []*RoomInfo {
	if x != nil {
		return x.Roomlist
	}
	return nil
}

//房间玩家信息
type RoomPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID      string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Rank     int32  `protobuf:"varint,3,opt,name=Rank,proto3" json:"Rank,omitempty"`
	IsReady  bool   `protobuf:"varint,4,opt,name=IsReady,proto3" json:"IsReady,omitempty"`
	IsOwner  bool   `protobuf:"varint,5,opt,name=IsOwner,proto3" json:"IsOwner,omitempty"`
	HeadIcon int32  `protobuf:"varint,6,opt,name=HeadIcon,proto3" json:"HeadIcon,omitempty"`
}

func (x *RoomPlayer) Reset() {
	*x = RoomPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayer) ProtoMessage() {}

func (x *RoomPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayer.ProtoReflect.Descriptor instead.
func (*RoomPlayer) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{11}
}

func (x *RoomPlayer) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *RoomPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomPlayer) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RoomPlayer) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *RoomPlayer) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *RoomPlayer) GetHeadIcon() int32 {
	if x != nil {
		return x.HeadIcon
	}
	return 0
}

type EnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag       bool          `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	PlayerList []*RoomPlayer `protobuf:"bytes,2,rep,name=PlayerList,proto3" json:"PlayerList,omitempty"`
}

func (x *EnterRoom) Reset() {
	*x = EnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoom) ProtoMessage() {}

func (x *EnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoom.ProtoReflect.Descriptor instead.
func (*EnterRoom) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{12}
}

func (x *EnterRoom) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *EnterRoom) GetPlayerList() []*RoomPlayer {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

// 发送各种是否成功或者标识指令
type Sync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag bool `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *Sync) Reset() {
	*x = Sync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{13}
}

func (x *Sync) GetTag() bool {
	if x != nil {
		return x.Tag
	}
	return false
}

type IsReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID   string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Ready bool   `protobuf:"varint,2,opt,name=Ready,proto3" json:"Ready,omitempty"`
}

func (x *IsReady) Reset() {
	*x = IsReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReady) ProtoMessage() {}

func (x *IsReady) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReady.ProtoReflect.Descriptor instead.
func (*IsReady) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{14}
}

func (x *IsReady) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *IsReady) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

//进入游戏
type EnterGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerList []*GamePlayer `protobuf:"bytes,1,rep,name=playerList,proto3" json:"playerList,omitempty"`
	Seed1      int32         `protobuf:"varint,2,opt,name=Seed1,proto3" json:"Seed1,omitempty"`
}

func (x *EnterGame) Reset() {
	*x = EnterGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGame) ProtoMessage() {}

func (x *EnterGame) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGame.ProtoReflect.Descriptor instead.
func (*EnterGame) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{15}
}

func (x *EnterGame) GetPlayerList() []*GamePlayer {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *EnterGame) GetSeed1() int32 {
	if x != nil {
		return x.Seed1
	}
	return 0
}

type GamePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	PID int32  `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
}

func (x *GamePlayer) Reset() {
	*x = GamePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayer) ProtoMessage() {}

func (x *GamePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayer.ProtoReflect.Descriptor instead.
func (*GamePlayer) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{16}
}

func (x *GamePlayer) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *GamePlayer) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

type GameTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeLeft int32 `protobuf:"varint,1,opt,name=TimeLeft,proto3" json:"TimeLeft,omitempty"`
}

func (x *GameTime) Reset() {
	*x = GameTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTime) ProtoMessage() {}

func (x *GameTime) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTime.ProtoReflect.Descriptor instead.
func (*GameTime) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{17}
}

func (x *GameTime) GetTimeLeft() int32 {
	if x != nil {
		return x.TimeLeft
	}
	return 0
}

//更新玩家分数
type PlayerPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID   string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Point int32  `protobuf:"varint,2,opt,name=Point,proto3" json:"Point,omitempty"`
}

func (x *PlayerPoint) Reset() {
	*x = PlayerPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPoint) ProtoMessage() {}

func (x *PlayerPoint) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPoint.ProtoReflect.Descriptor instead.
func (*PlayerPoint) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerPoint) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *PlayerPoint) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

//更新玩家分数
type PlayerKill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SUID  string `protobuf:"bytes,1,opt,name=SUID,proto3" json:"SUID,omitempty"`    //杀人者
	PUID  string `protobuf:"bytes,2,opt,name=PUID,proto3" json:"PUID,omitempty"`    //被杀者
	Point int32  `protobuf:"varint,3,opt,name=Point,proto3" json:"Point,omitempty"` //得分
}

func (x *PlayerKill) Reset() {
	*x = PlayerKill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerKill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerKill) ProtoMessage() {}

func (x *PlayerKill) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerKill.ProtoReflect.Descriptor instead.
func (*PlayerKill) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerKill) GetSUID() string {
	if x != nil {
		return x.SUID
	}
	return ""
}

func (x *PlayerKill) GetPUID() string {
	if x != nil {
		return x.PUID
	}
	return ""
}

func (x *PlayerKill) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

//测试移动
type BroadCastMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo []*Player `protobuf:"bytes,1,rep,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"`
}

func (x *BroadCastMove) Reset() {
	*x = BroadCastMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadCastMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastMove) ProtoMessage() {}

func (x *BroadCastMove) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastMove.ProtoReflect.Descriptor instead.
func (*BroadCastMove) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{20}
}

func (x *BroadCastMove) GetPlayerInfo() []*Player {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

//方块
type Cube struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID int32   `protobuf:"varint,1,opt,name=CID,proto3" json:"CID,omitempty"`
	Pos *Vector `protobuf:"bytes,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rot *Vector `protobuf:"bytes,3,opt,name=Rot,proto3" json:"Rot,omitempty"`
}

func (x *Cube) Reset() {
	*x = Cube{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cube) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cube) ProtoMessage() {}

func (x *Cube) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cube.ProtoReflect.Descriptor instead.
func (*Cube) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{21}
}

func (x *Cube) GetCID() int32 {
	if x != nil {
		return x.CID
	}
	return 0
}

func (x *Cube) GetPos() *Vector {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Cube) GetRot() *Vector {
	if x != nil {
		return x.Rot
	}
	return nil
}

type Cubes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CId []int32 `protobuf:"varint,1,rep,packed,name=CId,proto3" json:"CId,omitempty"`
}

func (x *Cubes) Reset() {
	*x = Cubes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cubes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cubes) ProtoMessage() {}

func (x *Cubes) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cubes.ProtoReflect.Descriptor instead.
func (*Cubes) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{22}
}

func (x *Cubes) GetCId() []int32 {
	if x != nil {
		return x.CId
	}
	return nil
}

//方块碰撞时
type CubeColl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID     int32   `protobuf:"varint,1,opt,name=CID,proto3" json:"CID,omitempty"`
	CubePos *Vector `protobuf:"bytes,2,opt,name=CubePos,proto3" json:"CubePos,omitempty"`
	PID     int32   `protobuf:"varint,3,opt,name=PID,proto3" json:"PID,omitempty"`
	Flag    bool    `protobuf:"varint,4,opt,name=Flag,proto3" json:"Flag,omitempty"` //true表示击中玩家，false表示击中地面
}

func (x *CubeColl) Reset() {
	*x = CubeColl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CubeColl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeColl) ProtoMessage() {}

func (x *CubeColl) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeColl.ProtoReflect.Descriptor instead.
func (*CubeColl) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{23}
}

func (x *CubeColl) GetCID() int32 {
	if x != nil {
		return x.CID
	}
	return 0
}

func (x *CubeColl) GetCubePos() *Vector {
	if x != nil {
		return x.CubePos
	}
	return nil
}

func (x *CubeColl) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *CubeColl) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

//游戏结算得分
type GameSettle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID      string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Score    int32  `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
	EXP      int32  `protobuf:"varint,4,opt,name=EXP,proto3" json:"EXP,omitempty"`
	Rank     int32  `protobuf:"varint,5,opt,name=Rank,proto3" json:"Rank,omitempty"`
	HeadIcon int32  `protobuf:"varint,6,opt,name=HeadIcon,proto3" json:"HeadIcon,omitempty"`
	AddEXP   int32  `protobuf:"varint,7,opt,name=AddEXP,proto3" json:"AddEXP,omitempty"`
}

func (x *GameSettle) Reset() {
	*x = GameSettle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSettle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSettle) ProtoMessage() {}

func (x *GameSettle) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSettle.ProtoReflect.Descriptor instead.
func (*GameSettle) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{24}
}

func (x *GameSettle) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *GameSettle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameSettle) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameSettle) GetEXP() int32 {
	if x != nil {
		return x.EXP
	}
	return 0
}

func (x *GameSettle) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GameSettle) GetHeadIcon() int32 {
	if x != nil {
		return x.HeadIcon
	}
	return 0
}

func (x *GameSettle) GetAddEXP() int32 {
	if x != nil {
		return x.AddEXP
	}
	return 0
}

//游戏结算得分数组
type GameSettleArr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllData []*GameSettle `protobuf:"bytes,1,rep,name=AllData,proto3" json:"AllData,omitempty"`
}

func (x *GameSettleArr) Reset() {
	*x = GameSettleArr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSettleArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSettleArr) ProtoMessage() {}

func (x *GameSettleArr) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSettleArr.ProtoReflect.Descriptor instead.
func (*GameSettleArr) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{25}
}

func (x *GameSettleArr) GetAllData() []*GameSettle {
	if x != nil {
		return x.AllData
	}
	return nil
}

//玩家说话
type TalkVoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID int32 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	VID int32 `protobuf:"varint,2,opt,name=VID,proto3" json:"VID,omitempty"`
}

func (x *TalkVoice) Reset() {
	*x = TalkVoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgdata_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkVoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkVoice) ProtoMessage() {}

func (x *TalkVoice) ProtoReflect() protoreflect.Message {
	mi := &file_msgdata_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkVoice.ProtoReflect.Descriptor instead.
func (*TalkVoice) Descriptor() ([]byte, []int) {
	return file_msgdata_proto_rawDescGZIP(), []int{26}
}

func (x *TalkVoice) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *TalkVoice) GetVID() int32 {
	if x != nil {
		return x.VID
	}
	return 0
}

var File_msgdata_proto protoreflect.FileDescriptor

var file_msgdata_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x70, 0x62, 0x66, 0x22, 0x4a, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x36, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x58, 0x50, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x58, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x65, 0x61,
	0x64, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x48, 0x65, 0x61,
	0x64, 0x49, 0x63, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x08, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x75, 0x63,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x25, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x7e, 0x0a, 0x06,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x03, 0x52, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x03, 0x52, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x48, 0x50, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x48, 0x50, 0x22, 0x32, 0x0a, 0x06,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x59, 0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x5a,
	0x22, 0x30, 0x0a, 0x0a, 0x48, 0x61, 0x76, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43,
	0x49, 0x44, 0x22, 0x48, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x74, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x69,
	0x64, 0x12, 0x29, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x44, 0x69, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x09, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x44, 0x69, 0x72, 0x22, 0x18, 0x0a, 0x04,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x52, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x4e, 0x75, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x0a,
	0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x49, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64,
	0x49, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x48, 0x65, 0x61, 0x64,
	0x49, 0x63, 0x6f, 0x6e, 0x22, 0x50, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x2f, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x66, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x54, 0x61, 0x67,
	0x22, 0x31, 0x0a, 0x07, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x22, 0x52, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x2f, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x65, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x53, 0x65, 0x65, 0x64, 0x31, 0x22, 0x30, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x08, 0x47, 0x61, 0x6d,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x65, 0x66,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x65, 0x66,
	0x74, 0x22, 0x35, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x55,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x55, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73,
	0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x56, 0x0a, 0x04, 0x43, 0x75, 0x62, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x49, 0x44, 0x12, 0x1d, 0x0a, 0x03,
	0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x03, 0x52,
	0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x03, 0x52, 0x6f, 0x74, 0x22, 0x19, 0x0a, 0x05, 0x43, 0x75,
	0x62, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x03, 0x43, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x08, 0x43, 0x75, 0x62, 0x65, 0x43, 0x6f, 0x6c,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x43, 0x49, 0x44, 0x12, 0x25, 0x0a, 0x07, 0x43, 0x75, 0x62, 0x65, 0x50, 0x6f, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x07, 0x43, 0x75, 0x62, 0x65, 0x50, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x46, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67,
	0x22, 0xa2, 0x01, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45,
	0x58, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x58, 0x50, 0x12, 0x12, 0x0a,
	0x04, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x52, 0x61, 0x6e,
	0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x64, 0x64, 0x45, 0x58, 0x50, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41,
	0x64, 0x64, 0x45, 0x58, 0x50, 0x22, 0x3a, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x41, 0x72, 0x72, 0x12, 0x29, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x66, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x07, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x2f, 0x0a, 0x09, 0x54, 0x61, 0x6c, 0x6b, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x56, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x56,
	0x49, 0x44, 0x2a, 0xc4, 0x03, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x49, 0x47, 0x4e, 0x55, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x47, 0x4e,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x4f, 0x4f, 0x4d, 0x49, 0x4e, 0x46, 0x4f,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x4f, 0x4f, 0x4d,
	0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x52, 0x4f, 0x4f, 0x4d, 0x10,
	0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x05,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x53, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x06, 0x12, 0x09, 0x0a,
	0x05, 0x48, 0x45, 0x41, 0x52, 0x54, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x14, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x54, 0x50, 0x49,
	0x44, 0x10, 0x15, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x4f, 0x41, 0x44, 0x4d, 0x41, 0x50, 0x10, 0x16,
	0x12, 0x0b, 0x0a, 0x07, 0x47, 0x41, 0x4d, 0x45, 0x46, 0x49, 0x4e, 0x10, 0x17, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x59, 0x4e, 0x43, 0x50, 0x48, 0x56, 0x10, 0x18, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x57,
	0x41, 0x56, 0x45, 0x57, 0x45, 0x41, 0x50, 0x4f, 0x4e, 0x10, 0x19, 0x12, 0x0d, 0x0a, 0x09, 0x50,
	0x4c, 0x41, 0x43, 0x45, 0x43, 0x55, 0x42, 0x45, 0x10, 0x1a, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x54,
	0x4b, 0x10, 0x1b, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4c, 0x4c, 0x49, 0x53, 0x49, 0x4f, 0x4e,
	0x10, 0x1c, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x44, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x1d,
	0x12, 0x09, 0x0a, 0x05, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x1e, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x52, 0x4f, 0x52, 0x4f, 0x4f, 0x4d, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x68, 0x12, 0x0e,
	0x0a, 0x0a, 0x42, 0x52, 0x4f, 0x49, 0x53, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x6a, 0x12, 0x10,
	0x0a, 0x0c, 0x42, 0x52, 0x4f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x7a,
	0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x52, 0x4f, 0x47, 0x41, 0x4d, 0x45, 0x54, 0x49, 0x4d, 0x45, 0x10,
	0x7b, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x52, 0x4f, 0x53, 0x59, 0x4e, 0x43, 0x50, 0x48, 0x56, 0x10,
	0x7c, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x52, 0x4f, 0x48, 0x57, 0x41, 0x56, 0x45, 0x57, 0x45, 0x41,
	0x50, 0x4f, 0x4e, 0x10, 0x7d, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x52, 0x4f, 0x50, 0x4c, 0x41, 0x43,
	0x45, 0x57, 0x45, 0x41, 0x50, 0x4f, 0x4e, 0x10, 0x7e, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x52, 0x4f,
	0x41, 0x54, 0x4b, 0x10, 0x7f, 0x12, 0x11, 0x0a, 0x0c, 0x42, 0x52, 0x4f, 0x43, 0x4f, 0x4c, 0x4c,
	0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x80, 0x01, 0x12, 0x10, 0x0a, 0x0b, 0x42, 0x52, 0x4f, 0x41,
	0x44, 0x44, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x81, 0x01, 0x12, 0x0d, 0x0a, 0x08, 0x42, 0x52,
	0x4f, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x82, 0x01, 0x42, 0x05, 0xaa, 0x02, 0x02, 0x50, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgdata_proto_rawDescOnce sync.Once
	file_msgdata_proto_rawDescData = file_msgdata_proto_rawDesc
)

func file_msgdata_proto_rawDescGZIP() []byte {
	file_msgdata_proto_rawDescOnce.Do(func() {
		file_msgdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgdata_proto_rawDescData)
	})
	return file_msgdata_proto_rawDescData
}

var file_msgdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgdata_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_msgdata_proto_goTypes = []interface{}{
	(MSGID)(0),            // 0: pbf.MSGID
	(*SignUp)(nil),        // 1: pbf.SignUp
	(*SignIn)(nil),        // 2: pbf.SignIn
	(*User)(nil),          // 3: pbf.User
	(*SignSucc)(nil),      // 4: pbf.SignSucc
	(*Player)(nil),        // 5: pbf.Player
	(*Vector)(nil),        // 6: pbf.Vector
	(*HaveWeapon)(nil),    // 7: pbf.HaveWeapon
	(*PlayerAtk)(nil),     // 8: pbf.PlayerAtk
	(*Room)(nil),          // 9: pbf.Room
	(*RoomInfo)(nil),      // 10: pbf.RoomInfo
	(*RoomList)(nil),      // 11: pbf.RoomList
	(*RoomPlayer)(nil),    // 12: pbf.RoomPlayer
	(*EnterRoom)(nil),     // 13: pbf.EnterRoom
	(*Sync)(nil),          // 14: pbf.Sync
	(*IsReady)(nil),       // 15: pbf.IsReady
	(*EnterGame)(nil),     // 16: pbf.EnterGame
	(*GamePlayer)(nil),    // 17: pbf.GamePlayer
	(*GameTime)(nil),      // 18: pbf.GameTime
	(*PlayerPoint)(nil),   // 19: pbf.PlayerPoint
	(*PlayerKill)(nil),    // 20: pbf.PlayerKill
	(*BroadCastMove)(nil), // 21: pbf.BroadCastMove
	(*Cube)(nil),          // 22: pbf.Cube
	(*Cubes)(nil),         // 23: pbf.Cubes
	(*CubeColl)(nil),      // 24: pbf.CubeColl
	(*GameSettle)(nil),    // 25: pbf.GameSettle
	(*GameSettleArr)(nil), // 26: pbf.GameSettleArr
	(*TalkVoice)(nil),     // 27: pbf.TalkVoice
}
var file_msgdata_proto_depIdxs = []int32{
	3,  // 0: pbf.SignSucc.UserInfo:type_name -> pbf.User
	6,  // 1: pbf.Player.Pos:type_name -> pbf.Vector
	6,  // 2: pbf.Player.Rot:type_name -> pbf.Vector
	6,  // 3: pbf.PlayerAtk.AttackDir:type_name -> pbf.Vector
	10, // 4: pbf.RoomList.roomlist:type_name -> pbf.RoomInfo
	12, // 5: pbf.EnterRoom.PlayerList:type_name -> pbf.RoomPlayer
	17, // 6: pbf.EnterGame.playerList:type_name -> pbf.GamePlayer
	5,  // 7: pbf.BroadCastMove.PlayerInfo:type_name -> pbf.Player
	6,  // 8: pbf.Cube.Pos:type_name -> pbf.Vector
	6,  // 9: pbf.Cube.Rot:type_name -> pbf.Vector
	6,  // 10: pbf.CubeColl.CubePos:type_name -> pbf.Vector
	25, // 11: pbf.GameSettleArr.AllData:type_name -> pbf.GameSettle
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_msgdata_proto_init() }
func file_msgdata_proto_init() {
	if File_msgdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignSucc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HaveWeapon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAtk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerKill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadCastMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cube); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cubes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CubeColl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSettle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSettleArr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgdata_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkVoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgdata_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgdata_proto_goTypes,
		DependencyIndexes: file_msgdata_proto_depIdxs,
		EnumInfos:         file_msgdata_proto_enumTypes,
		MessageInfos:      file_msgdata_proto_msgTypes,
	}.Build()
	File_msgdata_proto = out.File
	file_msgdata_proto_rawDesc = nil
	file_msgdata_proto_goTypes = nil
	file_msgdata_proto_depIdxs = nil
}
